import type { Metadata } from "next";
import { Montserrat } from "next/font/google"
import MenuHeader from "../components/Header";
import CustomFooter from "../components/Footer";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Intranet UNICAT",
  description: "Generated by TI UNICAT",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body style={{ margin: 0, height: '100vh', display: 'flex', flexDirection: 'column', fontFamily: 'Montserrat, sans-serif' }}>
        <MenuHeader />
        
        <main style={{ flexGrow: 1, minHeight: 0, maxHeight: '100%', overflow: 'hidden' }}>
          {children}
        </main>
        
        <CustomFooter />
      </body>
    </html>
  );
}
