import type { Metadata } from "next";
import { Montserrat } from "next/font/google"
import MenuHeader from "../components/Header";
import CustomFooter from "../components/Footer";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Intranet UNICAT",
  description: "Generated by TI UNICAT",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={`${montserrat.className} flex flex-col min-h-screen`}>
        <MenuHeader />
        
        <main className="flex-grow flex">
          {children}
        </main>
        
        <CustomFooter />
      </body>
    </html>
  );
}
