import type { Metadata } from "next";
import { Montserrat } from "next/font/google"
import MenuHeader from "../components/Header";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Intranet UNICAT",
  description: "Generated by TI UNICAT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={montserrat.className}>
        <MenuHeader />
        {children}
      </body>
    </html>
  );
}